services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: heuuu
      POSTGRES_USER: heuuu
volumes:
  db_data:
