services:
  nextjs:
    build: .
    restart: always
    expose:
      - "3000"

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - ./cert.pem:/cert.pem:ro
      - ./key.pem:/key.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nextjs
