import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Switch from '@mui/material/Switch'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        coucou
        <div>
          The current theme is: {true}
          <Switch defaultChecked checked={true} onChange={() => {}} />
          {/* <button onClick={() => setTheme('coucou')}>Light Mode</button>
          <button onClick={() => false}>Dark Mode</button> */}
        </div>
      </main>

      <footer></footer>
    </div>
  )
}

export default Home
