import type {
  GetServerSideProps,
  InferGetServerSidePropsType,
  NextPage,
} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
//import { article } from '../../../back/api/src/schema/article'

type article = {
  id?: number
  private?: boolean
  on?: string
  title?: string
  data?: string
}

export const getServerSideProps = async () => {
  const articles = (
    await (
      await fetch('http://127.0.0.1:3010/', {
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          query: `{ articles{id private on title data }}`,
        }),
      })
    ).json()
  ).data.articles as article[]
  console.log(articles[0])

  //console.dir(JSON.parse(articles[0]?.data || ''), { depth: undefined })
  return {
    props: {
      articles,
    },
  }
}

function Home(props: InferGetServerSidePropsType<typeof getServerSideProps>) {
  const dateTimezone = (date: string) => {
    const old = new Date(date)
    return new Date(old.getTime() - old.getTimezoneOffset() * 60 * 1000)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>coucou</div>
        <div>heuuu 1. 2. ? </div>
        <table>
          <thead>
            <tr>
              <th>id</th>
              <th>private</th>
              <th>on</th>
              <th>title</th>
              <th>data</th>
            </tr>
          </thead>
          <tbody>
            {props.articles.map(article => {
              return (
                <tr key={article.id}>
                  <th>{article.id}</th>
                  <th>{article?.private?.toString()}</th>
                  <th>
                    {article.on ? dateTimezone(article.on).toUTCString() : null}
                  </th>
                  <th>{article.title}</th>
                  <th>{article.data}</th>
                  {/* id: {article.id} | on:
                  {article.on ? dateTimezone(article.on).toUTCString() : null} |
                  data:
                  {article.data} */}
                </tr>
              )
            })}
          </tbody>
        </table>
      </main>
      <div></div>

      <footer></footer>
    </div>
  )
}

export default Home
